version: "3.4"

services:
  deephaven:
    build: .
    ports:
      - "${DEEPHAVEN_PORT:-10000}:10000"
    volumes:
      - ./data:/data
      - ./storage:/storage
    environment:
      - JAVA_OPTS=-Xmx4g
